config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :cities
  resources :tickets
  resources :concerts
  resources :albums
  resources :songs
  resources :members
  resources :bands

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/band.rb
class Band < ApplicationRecord
	has_one_attached :avatar
	has_many :members
	has_many :albums
	belongs_to :city
	has_many :concert_performers
	has_many :concerts, through: :concert_performers
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]
  before_action :set_cities

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
   # @cities = City.all.sort_by(&:name)
  end

  # GET /bands/1/edit
  def edit
  #  @cities = City.all.sort_by(&:name)
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    def set_cities
      @cities = City.all.sort_by(&:name)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name, :genre, :city_id, :avatar)
    end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<div class="container">
<%= form_with(model: band, local: true) do |form| %>
  <% if band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :genre %>
    <%= form.text_field :genre, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :City %>
    <%= form.collection_select(:city_id, @cities, :id, :name, {:include_blank => "Odaberi grad"}, {:class=>'form-control input-lg',:class=>"form-control", :id=>'city_id'})%>

  </div>

  <div class="field form-group">
    <%= form.label "Band logo" %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>
</div>

app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form', band: @band %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Bands</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Genre</th>
        <th>City</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @bands.each do |band| %>
        <tr>
          <td><%= band.name %></td>
          <td><%= band.genre %></td>
          <td><%= City.find(band.city_id).name %></td>
          <td><%= link_to 'Show', band %></td>
          <td><%= link_to 'Edit', edit_band_path(band) %></td>
          <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Band', new_band_path %>
</div>

app/views/bands/new.html.erb
<div class="container">
	<div class="jumbotron">
		<h1>New Band</h1>
	</div>
		<%= render 'form', band: @band %>

		<%= link_to 'Back', bands_path %>
	</div>
</div>

app/views/bands/show.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @band.genre %>
</p>

<% if @band.avatar.attached? %>
	<image src="<%= (url_for(@band.avatar)) %>">
<% end %>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>
</div>